### ISSUE TITLE
Review plssss

### ISSUE THREAD

**Issue by adithyapaib** [EddieHubCommunity/support#1018]
**Remove all personal data, otherwise the resume will be deleted.**
https://resume.adithyapai.com
Portfolio: https://adithyapai.com
Items we can review on a live stream:

- GitHub profile
- Open source project
- Portfolio
- Resume

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by rootritesh** [comment]
- In ur Resume, try to use blue color its looks cool instead of using pink color.
- At the header try to improve the right side of the content It is not looking good.
![image](https://user-images.githubusercontent.com/57373623/109602732-ade00900-7b46-11eb-8f4d-51767144c723.png)

- On the left side there is lots of empty space. Try to fill that.
![image](https://user-images.githubusercontent.com/57373623/109602660-8b4df000-7b46-11eb-8392-4814c4618e22.png)
- The Design of ur Portfolio is Great. I love that animation.
- The social media box looks too big.
![image](https://user-images.githubusercontent.com/57373623/109602922-0dd6af80-7b47-11eb-833c-2118f582f0d9.png)
- Use some delay in the hover at ur project section.
![image](https://user-images.githubusercontent.com/57373623/109603053-4a0a1000-7b47-11eb-9992-51b4e8a160c1.png)
- I Hope this may help U out

**Comment by adithyapaib** [comment]
ok sir let me change it

**Comment by eddiejaoude** [comment]
Thanks for submitting, I will review on a live stream soon 👍

**Comment by kulendu** [comment]
Oh wow @adithyapaib the cursor and the animation looks really cool 🤟

**Comment by Prathamesh-Shanbhag** [comment]
![Screenshot 2021-05-03 220407](https://user-images.githubusercontent.com/70568620/116904627-94009680-ac5b-11eb-8b5c-c03bf468c631.png)
Consider switching the navbar to another shade of white to keep a distinct boundary between the page!

**Comment by rohank2502** [comment]
I think the social logos look better if you put the logo to the left and links to the right  !!  In your Resume

**Comment by schmelto** [comment]
Really like the spinner lol 🚀 🤣

**Comment by eddiejaoude** [comment]
Review on live stream https://youtu.be/ugEJ8LBb1r0

Looks good, some thoughts...
- we love the pink and clean layout
- suggest having a single layout so the ATS machine can understand it better
- suggest having some of your open source projects on your resume
