### ISSUE TITLE
Make additional ISSUE_TEMPLATES for open source reviews

### ISSUE THREAD

**Issue by SashoStoichkov** [EddieHubCommunity/support#1179]
# Idea
I think we should create separate issue templates for:
- `GH Profile review`
- `Open Source Project review`
- `Portfolio review`
- `Resume review`

# Reason
This is to encourage people to send one link per issue so @eddiejaoude doesn't have to choose to review one out of two or three. For example when @eddiejaoude does a live stream for specific reviews - it'll be easier for him to filter out the specific type of reviews he is doing on that day.

# How to do it?
Just `copy&paste` this file -> `.github/ISSUE_TEMPLATE/resume-review.md` and rather writing this:
```
Items we can review on a live stream:

-> GitHub profile
-> Open source project
-> Portfolio
-> Resume
```

... write this:
```
Please review my {GitHub profile (for example)}: <insert link here>
```

# TODO List

- [x] `GH Profile review`
- [x] `Open Source Project review`
- [x] `Portfolio review`
- [x] `Resume review`

**Comment by eddiejaoude** [comment]
Great idea, thank you 👍

**Comment by nhcarrigan** [comment]
## Good First Issue

Thank you for reporting this issue. This looks something that can be fixed by first time contributors to this repository. If you have already made a contribution to this project, please reserve this issue for a new contributor.

Here are the steps to resolve this issue:

- Within the `.github/ISSUE_TEMPLATES` directory:
  - Create a file titled `gh-profile-review.md`
  - Create a file titled `portfolio-review.md`
  - Create a file titled `open-source-review.md`
  - Remove the file titled `review-my-open-source-link.md`
- Ensure that each of the three new files has the correct "frontmatter" at the top:

```md
---
name: (use a name that matches the file name)
about: Please review my (profile OR resume OR portfolio OR project) on a live stream
title: '[REVIEW]'
labels: (see labels below for this)
assignees: ''
---
```

In the front matter, apply the label that matches the template:
`resume review` or `portfolio review` or `gh profile review` or `open source review`.

Please make sure you read [our guidelines for contributing](../blob/main/CONTRIBUTING.md). If you have any questions about how to resolve this issue, or about the contributing process in general, [join us in our chat room](http://chat.nhcarrigan.com).

If you are interested in addressing this issue, reply here and we can assign the issue to you. If someone is already assigned to the issue, please allow them time to submit a pull request before requesting to be assigned yourself. Issues are typically unassigned after a week of inactivity.

**Comment by jainaayush01** [comment]
I would love to take this as my first contribution to the EddieHub.
Thanks for the beautiful documentation regarding the issue.

**Comment by SashoStoichkov** [comment]
@jainaayush01 do it 👍🏻 But also don't do the whole issue - spread the 🟩

**Comment by jainaayush01** [comment]
Okay

**Comment by Skyhero-admin** [comment]
Can I also try this
I want to try and do some contributions

**Comment by SashoStoichkov** [comment]
@Skyhero-admin Don't ask to do it - just do it 😉

**Comment by Skyhero-admin** [comment]
ohk

**Comment by AllanRegush** [comment]
The PR #1191 has removed the issue template for `review-my-open-source-link.md`

**Comment by SashoStoichkov** [comment]
Thank you all for the collaboration 👍🏻
