### ISSUE TITLE
[REVIEW] - Portfolio Website

### ISSUE THREAD

**Issue by starlightknown** [EddieHubCommunity/support#1292]
**Please ensure that you dont have any personal details in your Portfolio that you dont want to share publicly.**

Portfolio link: https://starlightknown.github.io/
Repo [here](https://github.com/starlightknown/starlightknown.github.io)

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by nicm42** [comment]
I really like how this looks when you open the link, with the laptop in the background and title coming up to the middle.

But I'm having trouble reading some of it. With the size I have my browser at, I can't read the text for your second and third Hackathons very well against the laptop background. I have the same problem reading the What I've Done section. But I'm fine reading the text on your cards in your about me section - those have a darker background. Maybe it's worth making all your cards have that darker background. My opinion is, you want people to read this and see how amazing you are, don't give them the excuse not to read it.

I have a similar problem reading the details of your projects - maybe make the backgrounds greyer rather than white, so the pictures don't show through quite so much.

**Comment by starlightknown** [comment]
Thank you, I get your point but have you tried hovering over the elements in those sections? The box becomes white making the text more readable. If that's not the issue could you share a screenshot ? It'll help to relate with what you said.

**Comment by nicm42** [comment]
Oh, yes, it is easier to read when hovering (aside from your project info). I just never thought to hover to read anything before.

**Comment by starlightknown** [comment]
Project info card pops up when you hover on the image too, similarly

**Comment by schmelto** [comment]
Hey @starlightknown 

really love your portfolio.

Maybe take a look on this behavior 
![image](https://user-images.githubusercontent.com/30869493/114931048-ff620000-9e35-11eb-86ad-387a809431ad.png)

You highlight the boxes on hover. I would expect that I can click on them like a link.

And maybe I will make something similar like you with the 100% viewport height for one topic that's really cool

**Comment by starlightknown** [comment]
Thank you and I'm not sure about the behaviour since I see it correct here, is this because of compatibility of devices for site?
![IMG_20210416_013743](https://user-images.githubusercontent.com/74637789/114932065-b3728380-9e54-11eb-932b-84d0e9972355.jpg) and should I add links to these?

**Comment by schmelto** [comment]
> Thank you and I'm not sure about the behaviour since I see it correct here, is this because of compatibility of devices for site?

Yes when resizing the window this issue appears. But unfortunately now I cannot recreate this issue strange 🤔 

> and should I add links to these?

I would add links to these 🚀

**Comment by nhcarrigan** [comment]
Thank you for sharing - we will review on a livestream when time allows :)

**Comment by starlightknown** [comment]
sure! thank you

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://youtu.be/tZJGPO432OQ

Looks AMAZING 😍 , some thoughts:
- AngelHack logo is a bit squish horizontally 
- suggest automate the releases, current release is 11 commits behind
- screenshot in the readme
- missing code of conduct
- suggest hiding packages and wiki if not using them
