### ISSUE TITLE
[REVIEW]: Please Review my Portfolio

### ISSUE THREAD

**Issue by yashsehgal** [EddieHubCommunity/support#1306]
**Please ensure that you don't have any personal details in your Portfolio that you don't want to share publicly.**

Portfolio link: https://yashsehgal.github.io/portfolio_v_2/

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Some suggestions from my side.


- Maybe take a look at the mobile view of your portfolio

![Screenshot_20210417_105129_com.android.chrome~2.jpg](https://user-images.githubusercontent.com/30869493/115107429-10605d80-9f6b-11eb-9493-3e8d1bcc368e.jpg)

- I would highlight the projects or education with a heading or making them bold

- and I think a navbar would be really nice to know what to expect on scrolling down your portfolio 

- was it intended to include social links at the top and at the bottom? 

Otherwise I really love the clean and simple design of your portfolio!

**Comment by yashsehgal** [comment]
> Some suggestions from my side.
> 
> * Maybe take a look at the mobile view of your portfolio

**Yeah, right now I am working on the responsiveness of my portfolio so it will be good on mobile devices too.**
> 
> ![Screenshot_20210417_105129_com.android.chrome~2.jpg](https://user-images.githubusercontent.com/30869493/115107429-10605d80-9f6b-11eb-9493-3e8d1bcc368e.jpg)

> * I would highlight the projects or education with a heading or making them bold

**Alright, This is a nice point, I will look into this.**

> * and I think a navbar would be really nice to know what to expect on scrolling down your portfolio

**Yeah Sure, I will try to make a UX like this 😃**

> * was it intended to include social links at the top and at the bottom?

**Yes, I did it so that the visitor can go to my profiles from both sections. Isn't it looking clean??**
> 
> Otherwise I really love the clean and simple design of your portfolio!

**Really thanks for the compliment**
> 
> Edit:
> 
> > I am Yash Sehgal, I am a Developer, A Designer and A Former Computer Science Student.
> 
> Take a look at the `a` / `A`

**Sure, I will do the listed changes**

Really appreciate your reviews. Thanks for your time :) 👍🏽 @schmelto

**Comment by schmelto** [comment]
> > * was it intended to include social links at the top and at the bottom?
> 
> **Yes, I did it so that the visitor can go to my profiles from both sections. Isn't it looking clean??**

Just wonder why the same information on two places but if this was intended from you I think you can keep it.

**Comment by vinzvinci** [comment]
Improve your layout design & also add light/dark mode features there if ever.

**Comment by yashsehgal** [comment]
> Improve your layout design & also add light/dark mode features there if ever.

Yeah Light/Dark feature would be great 😃

**Comment by felixfaisal** [comment]
I was going to bring up points about responsiveness and layout but since that's been done, 
I want to talk about the content of it 
It's very minimal information about yourself and to the point which Is really great, I know a lot of people that struggle to do that

I'd like to add something about the resume, I think you're using two different fonts, that's why the headers and the description do not look consistent. 

Overall, It's a great portfolio :)

**Comment by yashsehgal** [comment]
> I was going to bring up points about responsiveness and layout but since that's been done,
> I want to talk about the content of it
> It's very minimal information about yourself and to the point which Is really great, I know a lot of people that struggle to do that
> 
> I'd like to add something about the resume, I think you're using two different fonts, that's why the headers and the description do not look consistent.
> 
> Overall, It's a great portfolio :)

Yeah @felixfaisal, I need to change my Resume too it's being updated for so long. Thanks for reminding me 😃 👍🏽

**Comment by nhcarrigan** [comment]
Thank you for sharing - we will review on a livestream when time allows :)

**Comment by nhcarrigan** [comment]
No bot these need to stay.

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=XT3_O4jULRE

Looks great, here are some thoughts
- love the photo
- love the social links
- skills section is clear, however the hover felt like it was going to be clickable
- if possible feature 1 video and 1 blog post higher up so you stand out more (your favourite video for example)
