### ISSUE TITLE
[REVIEW] Voting System and Leaderboard

### ISSUE THREAD

**Issue by hrahul2605** [EddieHubCommunity/support#1324]
**Description**
A simple voting system, with a live leaderboard

**Project Link:**

Repo - https://github.com/hrahul2605/jv-client

Live at  - https://jv.hrahul2605.tech/

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by kaiwalyakoparkar** [comment]
Hey, @hrahul2605 Thanks for submitting. I would love to give you some suggestion
- Add  Code of conduct & Contributing MD's
- Add issue and pr template
- Add more screenshots of your working project in the readme
- Add actions to your project
- Add project board to plan new features and add milestones to them
- Add more and more issues for your upcoming plans so that the contributors can see what you are planning for the future of the project.
- Add manual or automated releases
- Add customized issue tags

**Comment by schmelto** [comment]
Nice one with the mobile view lol 😂

**Comment by kaiwalyakoparkar** [comment]
@schmelto Haha! you are right! I just checked the mobile view :rofl:

**Comment by hrahul2605** [comment]
@kaiwalyakoparkar Hey, thanks for the review, I'll do the needful.

lol yes I plan to do the mobile view soon enough :grin:

**Comment by kaiwalyakoparkar** [comment]
@hrahul2605 Can't wait to see that!

**Comment by krishdevdb** [comment]
This aint to be stale. @nhcarrigan maybe we use a older version of the actin, but supply the arguments for the newer versions. We are on actions/stale@v1 we should be on actions/stale@v3?

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=XT3_O4jULRE

- looks good
- deployed link is great
- no releases or tags
- suggest adding a code of conduct 
- suggest hiding packages and wiki if not used
- screenshot in the readme would be useful (extra points for animated gif)
- suggest using issues even if just you working on it

**Comment by Daggy1234** [comment]
Thank you for the feedback eddie! Much appreciated
