### ISSUE TITLE
[REVIEW] - GitHub Profile

### ISSUE THREAD

**Issue by suubh** [EddieHubCommunity/support#1356]
**Github Profile Link:**
https://github.com/suubh
Will love some suggestions in live stream 🙂.

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by kaiwalyakoparkar** [comment]
I would love to give some suggestions on your profile : 
- You can just change the color of your social buttons (Under programmer gif). because they are not visible when on dark mode.
- You can try removing the drop-down button as it adds complexity and is not friendly to someone who is new to GitHub and has landed on your profile. 
- Do include the templates, Actions, boards, license, code of conduct, contributing.md in your projects. They increase the credibility of your project

btw loved your work. :heart:

**Comment by suubh** [comment]
> I would love to give some suggestions on your profile :
> 
> * You can just change the color of your social buttons (Under programmer gif). because they are not visible when on dark mode.
> * You can try removing the drop-down button as it adds complexity and is not friendly to someone who is new to GitHub and has landed on your profile.
> * Do include the templates, Actions, boards, license, code of conduct, contributing.md in your projects. They increase the credibility of your project
> 
> btw loved your work. ❤️

Thank . I will change the color of social .

**Comment by nhcarrigan** [comment]
Thanks for sharing - we will review on a livestream as time allows :)

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://www.youtube.com/watch?v=w0ELpv3Z4Wk

Looks good, some thoughts:
- I think there are too many things that are animated, limit this to a few
- 100% commits, suggest doing code reviews, pull requests and issues
