### ISSUE TITLE
[REVIEW]

### ISSUE THREAD

**Issue by pvcodes** [EddieHubCommunity/support#1361]
Portfolio link: https://pvcodes.netlify.app

**Comment by kaiwalyakoparkar** [comment]
Hey, I have some suggestion for your profile:
- Instead of keeping the project section empty you can add any of your projects there (regardless of it's noteworthiness). In the future, you will definitely make good projects but don't keep them blank
- (On your GitHub profile) You can remove the drop-down and directly add the graphs and cards to your profile. Because it comes at a first glance when a user lands on your profile.
- Else everything is great and I appreciate your work.

**Comment by schmelto** [comment]
Love the portfolio! 🚀  May take a look at the mobile view of your website, the paragraphs are a little bit small.

**Comment by Vyvy-vi** [comment]
Interesting. Which one of the two is your main portfolio(Which one would you send to a potential employer)?

### Thought on the github.io portfolio-
- Well made and neat minimalistic design(I like the light-dark mode switch)
- Add some info about this in the repository for `pvcodes.github.io` (READMEs are nice. Maybe add a gif, maybe contribution guidelines). Also, maybe use commit messages that give more information.

### Thoughts on the netlify portfolio-
- It's really good and also compatible with mobile devices(though the text size has a few issues) :)
- Maybe you can put your projects on there. I had a quick look at your github, and you have got a few projects. Even if some of them are not 'notewothy', linking something would really help. Maybe deploy the html-css projects and then add them to your portfolio(those display your HTML skills).
- With small screens, the dropdown takes up all the space, but the scrollbar is still there. Not too big of an issue, but maybe it should be a smaller overlay or the scroll bar shouldn't be there when the dropdown is opened? 

Btw, love the consistent naming(pvcodes on all platforms)

### Extra feedback (linkedin/github)-
- Add more info in a bio on Linkedin. imo it gives a better idea about you and your interests. Moreover, it also helps with showing up on search results.
- The github readme `Visits` button tends to be slightly inaccurate, since it's just the no of loads of that site

- Deploy your HTML projects on Github Pages, link it in the description. This enables you to showcase it.
- Add READMEs, descriptions to your projects. These really help in giving more context.
- Better commit messages would be nice. Try to give more detail

**Comment by pvcodes** [comment]
> Hey, I have some suggestion for your profile:
> 
>     * Instead of keeping the project section empty you can add any of your projects there (regardless of it's noteworthiness). In the future, you will definitely make good projects but don't keep them blank
> 
>     * (On your GitHub profile) You can remove the drop-down and directly add the graphs and cards to your profile. Because it comes at a first glance when a user lands on your profile.
> 
>     * Else everything is great and I appreciate your work.
For sure! thanks for ur feedback

**Comment by pvcodes** [comment]
> Love the portfolio! rocket May take a look at the mobile view of your website, the paragraphs are a little bit small.

Definitely, I'll look into that, Also thanks for your feedback

**Comment by pvcodes** [comment]
> Interesting. Which one of the two is your main portfolio(Which one would you send to a potential employer)?
> ### Thought on the github.io portfolio-
> 
>     * Well made and neat minimalistic design(I like the light-dark mode switch)
> 
>     * Add some info about this in the repository for `pvcodes.github.io` (READMEs are nice. Maybe add a gif, maybe contribution guidelines). Also, maybe use commit messages that give more information.
> 
> 
> ### Thoughts on the netlify portfolio-
> 
>     * It's really good and also compatible with mobile devices(though the text size has a few issues) :)
> 
>     * Maybe you can put your projects on there. I had a quick look at your github, and you have got a few projects. Even if some of them are not 'notewothy', linking something would really help. Maybe deploy the html-css projects and then add them to your portfolio(those display your HTML skills).
> 
>     * With small screens, the dropdown takes up all the space, but the scrollbar is still there. Not too big of an issue, but maybe it should be a smaller overlay or the scroll bar shouldn't be there when the dropdown is opened?
> 
> 
> Btw, love the consistent naming(pvcodes on all platforms)
> ### Extra feedback (linkedin/github)-
> 
>     * Add more info in a bio on Linkedin. imo it gives a better idea about you and your interests. Moreover, it also helps with showing up on search results.
> 
>     * The github readme `Visits` button tends to be slightly inaccurate, since it's just the no of loads of that site
> 
>     * Deploy your HTML projects on Github Pages, link it in the description. This enables you to showcase it.
> 
>     * Add READMEs, descriptions to your projects. These really help in giving more context.
> 
>     * Better commit messages would be nice. Try to give more detail

TBH, I took the inspiration for 'github.io site' from this website http://jessieren.com/
and for readme's what can I add their, also for netlify site the navbar text is small or the https://pvcodes.netlify.app/#home is smaller, Yeah I've deployed my HTML pages using netlify pages

**Comment by nhcarrigan** [comment]
Thanks for sharing - we will review on a livestream as time allows :)

**Comment by pvcodes** [comment]
> Thanks for sharing - we will review on a livestream as time allows :)
> 
> Please note that we typically review only one project per issue. We recommend editing this issue to select only one of your projects, and creating a new issue for the other.

Yep I'll edit the issue!

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://www.youtube.com/watch?v=w0ELpv3Z4Wk

Looks good, some thoughts:
- The typing looks great, but might not be accessible 

Portfolio Repo:
- suggest making it like a real project as hiring managers will be looking at this more than the pretty portfolio
- suggest using issues in the repo, using labels will help get more contributors 
- hide features not being used like the `wiki`, `releases` and `packages`
- use `releases`/`tags`
