### ISSUE TITLE
[REVIEW] Reseter.css

### ISSUE THREAD

**Issue by krishdevdb** [EddieHubCommunity/support#1448]
**Project Link:**
https://github.com/krishdevdb/reseter.css

You can also join the discord community [here](http://discord.eddiehub.org): Did it already!

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity) Did Already. Will Check For Something New!

Thanks for reviewing our project. Thanks, @eddiejaoude. I watch your videos on youtube. They inspired me to get into open source and contribute to it. Your Videos are great!

**Comment by schmelto** [comment]
Wow looking great 🚀 

some suggestions from my side:

* remove redundant information in the readme
![image](https://user-images.githubusercontent.com/30869493/117563759-4b583b80-b0a8-11eb-9488-16e3da641ece.png)

* consider using conventional labels (consider using this action 👍🏼 https://github.com/EddieHubCommunity/gh-action-open-source-labels)


otherwise its looking good for me great work!

**Comment by krishdevdb** [comment]
> Wow looking great 🚀
> 
> some suggestions from my side:
> 
> * remove redundant information in the readme
>   ![image](https://user-images.githubusercontent.com/30869493/117563759-4b583b80-b0a8-11eb-9488-16e3da641ece.png)
> * consider using conventional labels (consider using this action 👍🏼 https://github.com/EddieHubCommunity/gh-action-open-source-labels)
> 
> otherwise its looking good for me great work!

Fixed Issue No 2.

But, Couldn't understand 1. There is no redundant information. Could you give examples?

**Comment by schmelto** [comment]
> But, Couldn't understand 1. There is no redundant information. Could you give examples?

Yeah the issue count Label and the GitHub stars are visible in github itself don't think this is needed in the readme as well hope this will explain this a little bit more

**Comment by eddiejaoude** [comment]
Thank you for sharing, I will review on a live stream soon 👍

**Comment by eddiejaoude** [comment]
Reviewing on a live stream https://www.youtube.com/watch?v=w0ELpv3Z4Wk

Looks good, some thoughts:
- README is amazing, maybe a bit too long, could remove things like the license as it is displayed already by GitHub 
- suggest moving the `wiki` to the `docs` folder in the repo, so that others can contribute and it can easily be reviewed via PRs etc for knowledge transfer
-

**Comment by krishdevdb** [comment]
> Reviewing on a live stream https://www.youtube.com/watch?v=w0ELpv3Z4Wk
> 
> Looks good, some thoughts:
> 
> * README is amazing, maybe a bit too long, could remove things like the license as it is displayed already by GitHub
> * suggest moving the `wiki` to the `docs` folder in the repo, so that others can contribute and it can easily be reviewed via PRs etc for knowledge transfer

@eddiejaoude how about I setting up a action using the git subtree command, so that the wiki can be pushed from the docs folder on a push. Meaning that wiki and the docs folder can work simutaneously together? I'll fix in the readme rn. Thanks
