### ISSUE TITLE
[REVIEW] Plz review it

### ISSUE THREAD

**Issue by harekrishnarai** [EddieHubCommunity/support#1472]
**Github Profile Link:**
https://github.com/harekrishnarai

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Really like it! 🚀 

may some suggestions.
* remove the view counter
* take a look at spacing

![image](https://user-images.githubusercontent.com/30869493/116908437-319b9c00-ac43-11eb-87df-cfc8105188f5.png)

**Comment by ashwinexe** [comment]
Its pretty impressive,
But many icons in are not dark mode friendly.

**Comment by harekrishnarai** [comment]
@schmelto @ashwinexe I'll surely consider it 😁

**Comment by saileshbro** [comment]
hi, @harekrishnarai may be you can change the layout too. It's better if we see all the information without having to scroll. I see lots of empty space too.
Just a suggestion.

**Comment by harekrishnarai** [comment]
Okay!!

**Comment by eddiejaoude** [comment]
@harekrishnarai did you mean to close this? It has not been reviewed on a live stream yet. Feel free to re-open it

**Comment by harekrishnarai** [comment]
Okay, Let reopen it! 🐙

**Comment by eddiejaoude** [comment]
Thank for sharing, reviewed on live stream https://www.youtube.com/watch?v=Hx5s0IqvfL4

Looks great, some of our thoughts:
- join EddieHubCommunity Org 😉 
- suggest removing your name on the customise GitHub profile because it is on the left
- remove 2nd horizontal line 
- profile is quite long, suggest making more use of the white space
   - removing some of the widgets
   - duplicate repo (widget and pinned repos)
