### ISSUE TITLE
[REVIEW] Portfolio + GitHub Profile Review

### ISSUE THREAD

**Issue by anishagg17** [EddieHubCommunity/support#1602]
Portfolio link: https://anishagg17.github.io/
GitHub Profile link: https://github.com/anishagg17

**Comment by schmelto** [comment]
Lol I love your portfolio someone with a terminal 🚀🚀🚀

Onyl some small suggestions take a look tmat the mobile view ![Screenshot_20210511_220218.jpg](https://user-images.githubusercontent.com/30869493/117877285-aa829f80-b2a4-11eb-8dec-7320a9ddc4cc.jpg)
And maybe consider the commands in the terminal also usable with uppercase letters otherwise wow man I really like it

**Comment by shubhendumadhukar** [comment]
A trivial but best part that I liked was if you try to scroll past the end of the page the %age badge on About page shows more than 100% 👍 Not sure if it works on all the devices, I was on a Mac with Safari. Still nice touch!

I know this is a small thing, but since I have an OCD for design, the tiles on 'My Work' pages are not uniform/same size. Other than that amazing work!

<img width="1789" alt="Screenshot 2021-05-12 at 7 59 28 AM" src="https://user-images.githubusercontent.com/10685907/117909543-10e4dd80-b2f8-11eb-9c84-d82fefda851b.png">

**Comment by Ayush7614** [comment]
> Portfolio link: https://anishagg17.github.io/
> GitHub Profile link: https://github.com/anishagg17

@anishagg17 bro i have some suggestion for you regrading github profiles you can added more features in it like you can add languages and framework with proper big big boxes like this is seen in my this github profile
![image](https://user-images.githubusercontent.com/67006255/118594228-b8658280-b7c6-11eb-9c46-ae071646df70.png)

and plss increase the size of social media icons 
![image](https://user-images.githubusercontent.com/67006255/118594146-8d7b2e80-b7c6-11eb-9032-14c35aeb839e.png)

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=8SmgE7X9yHg 

Looks good, some of our thoughts
- you have not joined EddieHub 😢 
- great to see the technology break down in your customised profile
- I am not a fan of profile views badge
- the website looks great, and the terminal is fun
