### ISSUE TITLE
[REVIEW] https://niloysikdar.github.io/

### ISSUE THREAD

**Issue by niloysikdar** [EddieHubCommunity/support#1713]
**Please ensure that you dont have any personal details in your Portfolio that you dont want to share publicly.**

Portfolio link: https://niloysikdar.github.io/

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by animeshbhakat** [comment]
Hello @niloysikdar.. your portfolio looks really good.
- Things I liked
    - Clean design
    - everything was in place
    - some simple but effective transition animation.
    - every project's GitHub/playstore link is given
- My suggestions
    - consider removing the "portfolio" written in the upper left corner. You can put your full name there.

**Comment by kaiwalyakoparkar** [comment]
hey, @niloysikdar, Great work! I would love to suggest to you something. 
- Change the title to your name
![Screenshot from 2021-05-21 11-05-47](https://user-images.githubusercontent.com/53310847/119087734-3b841400-ba25-11eb-8910-60531ea9a72d.png)
- Add some transition to your Resume button. Some delay while the color change will be good
![resumeTransition](https://user-images.githubusercontent.com/53310847/119087841-62dae100-ba25-11eb-9792-11f9005b2a74.png)
- Install a lighthouse extension on your chrome browser and try to improve on the mentioned things. your current score is
![Lighthouse](https://user-images.githubusercontent.com/53310847/119087957-82720980-ba25-11eb-942c-5fa1a84bd8a1.png)

**Comment by schmelto** [comment]
Maybe take also a look at the mobile view of your website
![Screenshot_20210521_080025.jpg](https://user-images.githubusercontent.com/30869493/119089580-ad029900-ba0a-11eb-94cd-3c5a7127e7f1.jpg)

Overflow in the heading here.

Otherwise and with the comments above it looks very good

**Comment by niloysikdar** [comment]
Thanks, @animeshbhakat , @kaiwalyakoparkar , @schmelto for the suggestions, I will definitely try to implement them.

**Comment by kaiwalyakoparkar** [comment]
@niloysikdar Your profile will get reviewed in the stream soon!

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by krishguptadev** [comment]
# Possible Improvements

## UI Issues

### Too much whitespace in Hero

**Screenshot(s)**: ![image](https://user-images.githubusercontent.com/91655303/142749911-309e4fac-745e-4b9e-ae57-5e5895246fcd.png)

**Suggested Fix**: Enlarge content and images.

### Too many colours

**Screenshot(s)**: ![image](https://user-images.githubusercontent.com/91655303/142750040-3824d0cf-ceb5-4aa4-beb0-e9bcb816dd7c.png)

**Suggested Fix**: Use the same color as in the button and hero text and remove the background of the SVG

### Site Name missing

**Screenshot(s)**: ![image](https://user-images.githubusercontent.com/91655303/142750044-757658b5-1789-4879-af28-405086ff1975.png)

**Suggested Fix**: Make it show `Niloy` instead of `Portfolio`

### Alignment Issues

**Screenshot(s)**: ![image](https://user-images.githubusercontent.com/91655303/142750075-42b8767b-4b83-4a81-b68f-3b143e56a82a.png) ![image](https://user-images.githubusercontent.com/91655303/142750085-98ce94a9-3614-4e7e-afca-b5df34d1043d.png) ![image](https://user-images.githubusercontent.com/91655303/142750090-e05d468f-8e26-4537-9a19-c51888210a1b.png) ![image](https://user-images.githubusercontent.com/91655303/142750092-4f9df1db-0194-45aa-8678-fc85f6e4cc72.png) ![image](https://user-images.githubusercontent.com/91655303/142750112-57b5143a-ab86-4d7d-9512-3354c707af9a.png) ![image](https://user-images.githubusercontent.com/91655303/142750113-59babc8a-8ff7-4ed2-a3b7-9074068d1c60.png)

**Suggested Fix**: Align everything to the navbar just like we have margins in our notebooks.

### Visual Hierarchy Issues

**Screenshot(s)**: ![image](https://user-images.githubusercontent.com/91655303/142750152-0266af2e-1b42-41d9-944d-1690ff730261.png) ![image](https://user-images.githubusercontent.com/91655303/142750155-1c07ced7-10d3-4dbf-b397-23f096260534.png) ![image](https://user-images.githubusercontent.com/91655303/142750158-42cea3b3-e533-4120-a87c-f47b7ed53e5a.png)

**Suggested Fix**: Make the less important elements, more gray and less saturated/bright

## UX Issues

### Contrast Issues

**Screenshot(s)**: ![image](https://user-images.githubusercontent.com/91655303/142750205-3759d569-7c31-48b8-ac55-aff2518bdb44.png)

**Suggested Fix**: Use a darker colour here.

### Image Alt Missing

**Screenshot(s)**: ![image](https://user-images.githubusercontent.com/91655303/142750242-ab22aee4-4422-4e1d-b409-13fdb44c3366.png)

**Suggested Fix**: Add an alt tag, even if it is empty else the file name is read by the screen readers

### Non-text Links missing aria-label

**Screenshot(s)**: ![image](https://user-images.githubusercontent.com/91655303/142750305-6e0d87a0-e4c2-4cdd-9212-ffddb859ad10.png)

**Suggested Fix**: Add a description to them using an aria-label tag


# Note

I have noticed that you have changed your portfolio but deleted the old repo, it would be nice if you could just save the portfolio there archived for others to learn 🙂

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://www.youtube.com/watch?v=xsZIKzE7gy8

Looks great, some thoughts
- maybe the squares should be green to be clear that it is related to github 
- open source projects first, education last
- picked the discord bot, no readme - readme is the most important file in the repo
