### ISSUE TITLE
[REVIEW] vikkastiwari

### ISSUE THREAD

**Issue by vikkastiwari** [EddieHubCommunity/support#1716]
**Github Profile Link:**

https://github.com/vikkastiwari

Portfolio link: https://iamvikkastiwari.web.app/

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by kaiwalyakoparkar** [comment]
Hey @vikkastiwari, I liked your profile. But I have few suggestions for you.
- Remove the profile view badge (Because it is manipulatable)
- You can write more in your about section
- You can move the reach out to me section below the about section
- Categorize your tool badges according to frontend backend etc
- Add description to your pinned project. That looks incomplete in the first glance
- Also add relevant tags to your projects too.

Thanks for submitting. You profile will get reviewed in the stream as time permits :)

**Comment by schmelto** [comment]
Love your portfolio website

**Comment by vinzvinci** [comment]
You got a good profile 👍

**Comment by Sam-Varghese** [comment]
Loved the profile and portfolio website. A small suggestion from my side, that you may consider replacing `AND A` with `AND AN` mentioned below your name

![image](https://user-images.githubusercontent.com/79152648/121785830-bd58fe80-cbd9-11eb-8c30-3c015bc16776.png)

**Comment by eddiejaoude** [comment]
Thank you for sharing, we will review on a live stream soon 👍 It looks like you are getting great community feedback already 💥

**Comment by eddiejaoude** [comment]
Reviewed on a video, coming out soon

Looks great, some feedback...
- Great professional photo
- Member of EddieHub 🎉 
- Good use of white space in the README
- Suggestion removing the top badges and moving the socials badges up
