### ISSUE TITLE
[REVIEW]

### ISSUE THREAD

**Issue by krishdevdb** [EddieHubCommunity/support#1769]
**Github Profile Link:**
@krishdevdb 

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of the EddieHub Community [here](https://github.com/EddieHubCommunity)

**Comment by schmelto** [comment]
Boja @krishdevdb 🚀

OK some thoughts.

Don't know why you link to your github profile here?
![Screenshot_20210601_064905_com.github.android.jpg](https://user-images.githubusercontent.com/30869493/120268164-a0513100-c2a5-11eb-8354-81cad0745f34.jpg)

Take a look at your projects if there is no description it looks little bit wired

![Screenshot_20210601_064929.jpg](https://user-images.githubusercontent.com/30869493/120268210-b65ef180-c2a5-11eb-9167-fd076ab08bae.jpg)

Due you pinned the open source projects in github I'm not sure if there needed in the readme.

Otherwise I really like the profile

**Comment by vinzvinci** [comment]
Some thoughts:

- Reduce the size 
![image](https://user-images.githubusercontent.com/73097560/120425501-e808b300-c3a0-11eb-9a1c-18d119117f21.png)

~~-~~
- Put your GitHub stats and GitHub streak together `(in one line)`

**Comment by krishdevdb** [comment]
Closing this issue, cause I need to work on it a lot after seeing you're reviews! Anyways I will submit this for review again once I'm done!

**Comment by vinzvinci** [comment]
Nooo don't submit again, your profile will back on top. Open this issue, and wait for another live stream review. You can still work for your GitHub profile and make changes.

**Comment by krishdevdb** [comment]
> Nooo don't submit again, your profile will back on top. Open this issue, and wait for another live stream review. You can still work for your GitHub profile and make changes.

I want to make sure breaking changes soon, I don't think my profile will be just ready till the time Eddie reviews it 😅
