### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Dhriti-Roy** [EddieHubCommunity/support#1904]
Please invite me to the GitHub Community Organisation.

- #### Name: Dhriti Roy

- #### Discord Username(if exists):

- #### Additional Context:

:nerd_face:

**Comment by eddiejaoude** [comment]
@Dhriti-Roy I think the bot failed because you are already part of the `EddieHubCommunity` Organisation.

Yep you are part of our GitHub Org, I will close this issue. Any issues let us know 🤓 

<img width="1457" alt="Screenshot 2021-06-26 at 18 49 26" src="https://user-images.githubusercontent.com/624760/123521546-4169b680-d6af-11eb-9d54-9ac15b02103c.png">

**Comment by krishdevdb** [comment]
Welcome to EddieHub 🤓
