### ISSUE TITLE
[REVIEW] Git auto badger 

### ISSUE THREAD

**Issue by technikhil314** [EddieHubCommunity/support#2108]
### Project link

https://github.com/technikhil314/auto-badger

**Comment by eddiejaoude** [comment]
Reviewed your GitHub Profile on live stream https://www.youtube.com/watch?v=gN9SWGV8YME

Looks great some thoughts:
- animated gif 💥 
- clear up some of the old PRs and branches
- use releases instead of tags
- autogenerate releases with GitHub Action (and changelog from your commits) example: https://github.com/EddieHubCommunity/api
- if not using the wiki, suggest hiding the tab in settings
- if not using packages, suggesting hiding in settings
- suggest removing duplicate badges (issues, forks)
- table of contents is no longer required as github generators this
