### ISSUE TITLE
[REVIEW] heysujal

### ISSUE THREAD

**Issue by heysujal** [EddieHubCommunity/support#2232]
### GitHub Profile Link

https://github.com/heysujal

**Comment by krishdevdb** [comment]
## Requested Changes 😉
- [ ] Make good use of space, the big image can be a whole lot smaller (IMO it Is not needed)
- [ ] Profile views badge can be removed since it is inaccurate
- [ ] Codeforces and some other logos won't appear in dark mode
- [ ] I'll rather not be having 3 stat images
- [ ] The Twitter follow badge isn't required if you have Twitter in the connect section
- [ ] I'll rather use GitHub settings customization options, like bio

## Feedback
- [x] Love your visual hierarchy ❤️ 
- [x] Love you are in EddieHub org 😍 
- [x] I personally like your profile, simple, sophisticated, and information 🤩 

**Copy This Checklist Paste It Into An Comment Then Keep It Updated With Your Workflow. I will update mine once I see your checklist is updated 😃**

**Comment by Panquesito7** [comment]
Hey, @heysujal! Great profile! I liked it a lot! I've made
a [**pull request**](https://github.com/heysujal/heysujal/pull/2) for minor improvements in the `README.md` file. 🙂

Thank you for sharing your awesome profile with the community! 😄

**Comment by Panquesito7** [comment]
@heysujal, if you close this PR, it won't be reviewed in a live stream. Re-open the issue if you want this to get reviewed in a live stream. 🙂

**Comment by eddiejaoude** [comment]
Looks great, some thoughts

- Maybe add more to the profile bio
- Widgets take a lot of space, maybe use 1 less
- Maybe pin 4 repos instead of 6
- 100% are commits try to do other areas, like code review


Review live stream https://www.youtube.com/watch?v=NxxJ_5nyG9E
