### ISSUE TITLE
[REVIEW]please review my portfolio on live stream 

### ISSUE THREAD

**Issue by Krishnapro** [EddieHubCommunity/support#2521]
### Portfolio link

https://krishnapro.github.io/

**Comment by emmalearnscode** [comment]
Love the colours, good layout and nice use of whitespace. Also great that your site works well with keyboard navigation. The only thing that I didn't notice at first was that you had more than one project, I'd suggest having them all visible on the screen instead of using the carousel as it's easy to miss the arrows. Make sure to add aria labels to any links which only use icons in order to make them more accessible.

**Comment by eddiejaoude** [comment]
Reviewed on live stream

Repo link https://github.com/Krishnapro/Krishnapro.github.io

- Design looks great
- Suggest using 2 different photos not the same one 
- Not sure what the progress bars mean
- Maybe centre the email contact as everything else is entered
- Love the timeline

**Comment by Krishnapro** [comment]
@eddiejaoude thank you for reviewing my portfolio and for your suggestion.
