### ISSUE TITLE
[REVIEW] cankush625

### ISSUE THREAD

**Issue by cankush625** [EddieHubCommunity/support#2561]
### GitHub Profile Link

https://github.com/cankush625

**Comment by Panquesito7** [comment]
Awesome profile, @cankush625! I liked it a lot! 🚀

I have made a [**pull request**](https://github.com/cankush625/cankush625/pull/1) in your repository for
some minor improvements in the `README.md` file. 🙂

Thank you for sharing your awesome profile with the community! 😄

**Comment by cankush625** [comment]
Hey @Panquesito7, I'm glad you liked it. Thanks for the improvements in the readme. I will take a look at it.

**Comment by krshkun** [comment]
Hi there 👋 I have a few suggestions and improvements for your profile

## 📝 Suggestions

- [ ] The profile views button doesn't add value IMHO: https://github.com/cankush625/cankush625/pull/2
- [ ] Collapsible for projects because you have pins as well
- [ ] Your name is there is the left column, no need to have a heading on the readme: https://github.com/cankush625/cankush625/pull/3
- [ ] The github profile trophy can be configured to be onelined
- [ ] The unicode characters make it difficult for screen readers: https://github.com/cankush625/cankush625/pull/4
- [ ] You can have a unified color scheme for the profile

## 🤔 Questions

- Some of the images are broken:
![image](https://user-images.githubusercontent.com/91655303/194847006-22016dc7-86e1-4541-b0ae-d5ad8043454b.png)
![image](https://user-images.githubusercontent.com/91655303/194847022-5f5aca3b-c394-44c5-92a5-89713655a98e.png)


## 🚀 Appreciation

- [x] Cool github profile

**Comment by eddiejaoude** [comment]
Reviewed on live stream...

Looks good, some thoughts:
- first widget seems broken
- lots of other missing images
- suggest trying to do more code reviews, issues and pull requests
