### ISSUE TITLE
[REVIEW] Asmit2952

### ISSUE THREAD

**Issue by Asmit2952** [EddieHubCommunity/support#2831]
### GitHub Profile Link

https://github.com/Asmit2952

**Comment by eddiejaoude** [comment]
Looks great, reviewed on a live stream, here is some feedback

- banner loops but the animation jumps, try to make a seamless loop on the animation (or use an intentional glitch)
- widgets take up a lot of space, suggest removing
- suggest removing all 8 widget repos as you have 6 pinned repos already - I think this is too much
