### ISSUE TITLE
[REVIEW] resume 

### ISSUE THREAD

**Issue by helper-uttam** [EddieHubCommunity/support#2909]
### Resume link

https://github.com/helper-uttam/portfolio/blob/master/assests/Resume.pdf

**Comment by emmalearnscode** [comment]
Nice clean layout and well aligned, good use of space 👍 Here’s a few ideas for improvement:

- capital letter on kumar 
- I’m not really sure what the coursework section represents, could you put links to coursework projects instead? 
- I would suggest changing the order, having projects and open source on the left and skills/tools/frameworks etc on the right in order to bring more focus to the most important things (as we read left to right it’s best to have most important on the left)
- Can you add Repo links to projects so it’s easy to get to the code?

**Comment by eddiejaoude** [comment]
Looks good, some suggestions reviewed in video coming out soon on my youtube channel http://youtube.com/eddiejaoude

- make the open source section appear sooner
- include links in the open source section (to projects or issues or pull requests)
