### ISSUE TITLE
[REVIEW] Portfolio

### ISSUE THREAD

**Issue by avneesh0612** [EddieHubCommunity/support#2995]
### Portfolio link

https://www.avneesh.tech/

**Comment by krishguptadev** [comment]
- Add an image or something in the right section of the hero
- A hover animation that turns the testimonial cards back to normal (not-diagonal) would be a nice addition
- A profile pic for the testimonial authors and link to their profile or something?

I do not know much about portfolios since I do not have one, so sorry I can't say any more 😅

**Comment by avneesh0612** [comment]
Those are some great ideas, thanks! Idk what can I do with the first point but will definitely implement the 2nd and 3rd 💯

**Comment by hellodeborahuk** [comment]
It looks great! You could move your photo up to the hero section? This would also remove the empty white space where the image is pushing down the skills section.

It depends who your target audience is but I'd change the order. If it's recruiters I'd move projects up and about me & testimonials down. You want them to see the most important things first. If you want to get clients, then testimonials is good at the top, I think they'd still want to see what you've done though so moving the projects up again. 

There's a space missing in the hero after full stack developer. 

I'd also consider a form for contact. 

I love the animation you've got going on.

**Comment by avneesh0612** [comment]
Hey, @hellodeborahuk I will move the image up. And I don't really have a targetted audience right now but I will move the projects up yeah.

I didn't add a contact form because it is mostly just spam. So I just added ways to contact me. Thanks :D

**Comment by avneesh0612** [comment]
So how is this order-
1. About
2. Testimonials
3. Work
4. Skills
5. Contact

**Comment by avneesh0612** [comment]
Hey, I have added some changes. Any other feedback is welcome :) https://www.avneesh.tech/

**Comment by emmalearnscode** [comment]
Looks great! Just a couple of things I noticed:

- you’ve got some sideways glide on mobile/iPad because of the projects section
- Everything else is left aligned but the contact section is center aligned and it is slightly jarring to the eye 
- Don’t downplay your skills by saying that you’re a school kid in your intro, I’d suggest taking it out.

**Comment by avneesh0612** [comment]
Ahem, nice suggestions. Thanks @emmalearnscode

**Comment by helper-uttam** [comment]
@avneesh0612  I loved your portfolio! How about adding some transition delay to the button: hover effect?

**Comment by avneesh0612** [comment]
Hey @helper-uttam thanksm which button are you talking about?

**Comment by avneesh0612** [comment]
Btw, here is the repository- https://github.com/avneesh0612/portfolio-template

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/i2t50B5lmIU

Looks good, some thoughts
- have releases
- use github actions for: build, lint, releases, deploy
- maybe add automated e2e testing

**Comment by avneesh0612** [comment]
Thanks for reviewing, added releases, and GitHub actions! Have created an issue for e2e testing, if it stays open for sometime I will learn about testing and implement it :)
