### ISSUE TITLE
[REVIEW] anubha-v-ardhan

### ISSUE THREAD

**Issue by anubha-v-ardhan** [EddieHubCommunity/support#3041]
### GitHub Profile Link

https://github.com/anubha-v-ardhan

**Comment by hellodeborahuk** [comment]
Hi Anubhav, I like your profile. Is there an emoji you could add to the second bullet point so they're all consistent. 
For the blog, it feels a bit of a waste of space, what about writing the article title instead of the logo and link to that article. Then when you have more articles on hashnode you could have a list of your top 3 or so posts.
