### ISSUE TITLE
[REVIEW] portfolio

### ISSUE THREAD

**Issue by thelabuzov** [EddieHubCommunity/support#3049]
### Portfolio link

https://thelabuzov.github.io/thelabuzov

**Comment by emmalearnscode** [comment]
Wow, great design @codlipa ! It looks really slick and works really nicely. Just a few suggestions:

- I couldn't find anywhere to turn the music off and it would be good if that was possible.
- Progress bars don't really mean anything - what does 99% HTML mean?
- In your projects you have some empty h2 tags which is bad practice for accessibility
- Your main tag only includes contact information, so the main content is not found inside the correct tag 
- You have no focus styling so it's really difficult to navigate your site by keyboard as you can't see which element is in focus

**Comment by codlipa** [comment]
Thank you very much for the suggestions, to be honest I want to add turn music off button for a long time, just not much time 😅
These bars similar to the progress as in a video game and they mean knowledge of skills (but it's not clear and I'll fix it soon)
Your suggestions helped me a lot, because this is exactly what I needed. I'll fix some problems soon, thanks again.
