### ISSUE TITLE
[REVIEW] Kira272921

### ISSUE THREAD

**Issue by 0xMukesh** [EddieHubCommunity/support#3071]
### GitHub Profile Link

https://github.com/kira272921

**Comment by Kira272921** [comment]
I have added a banner, need opinions about the banner 😄

**Comment by shubhimainalli** [comment]
Hey @Kira272921 amazing profile love the way your doing all this at 15 so inspiring

**Comment by Kira272921** [comment]
> Hey @Kira272921 amazing profile love the way your doing all this at 15 so inspiring

Thanks a lot for the kind words :D

**Comment by schmelto** [comment]
## Profile Review
### TLDR;

Your profile looks awesome! See the full details with my suggestions below.

---

### Full details

Your profile looks awesome! Here some suggestions from my side:

- consider adding links to the websites of the used techstacks
- consider making the Profile Stats a colabsable

Otherwise lit 🚀

**Comment by Kira272921** [comment]
@schmelto Thanks for the valuable feedback

**Comment by eddiejaoude** [comment]
Closing as profile 404 not found
