### ISSUE TITLE
[REVIEW] Sarah Lean

### ISSUE THREAD

**Issue by weeyin83** [EddieHubCommunity/support#3127]
### GitHub Profile Link

https://github.com/weeyin83

**Comment by Kira272921** [comment]
Hey 👋, Your portfolio seems really good to me 

Here are few changes needed to be done 
- The spacing between the icons in the `toolbox` section isn't properly done 
- It would be better if badges are just  instead of the icons, [here](https://github.com/Ileriayo/markdown-badges) is a great repository which contains list of various kinds of README badges

**Comment by eddiejaoude** [comment]
Looks good, some suggestions
- banner looks good but maybe half the height or add more text to the blank space (for example technologies)
- suggest removing the widget
- also try to do other contributions in addition to commits
