### ISSUE TITLE
[REVIEW] PrajwalBorkar

### ISSUE THREAD

**Issue by PrajwalBorkar** [EddieHubCommunity/support#3222]
### GitHub Profile Link

https://github.com/PrajwalBorkar

**Comment by AmrMonier** [comment]
You currently don't have a profile you can start creating a repo with the your username as the repo name and add a **README.md** file to it and modify its content and it would appear on your profile feel free to look at mine or any of the other amazing profiles in the awesome profiles repo on the Eddie community

**Comment by Pradumnasaraf** [comment]
Hey, @Pankaj-SinghR, thank you for opening an Issue.
#### Here are some of my recommendations -
- consider adding a profile page, for help you can also refer to Github's [official docs](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme) 
- Instead of Avatar, use your picture (It man be for privacy reasons, then ignore this :) )
- Add Bio
- More contributions :)

If you need any kind of help, ping us here or on Discord [server](https://discord.com/invite/jZQs6Wu)
