### ISSUE TITLE
[REVIEW] Muhammed-Rahif

### ISSUE THREAD

**Issue by Muhammed-Rahif** [EddieHubCommunity/support#3240]
### GitHub Profile Link

https://github.com/Muhammed-Rahif

**Comment by Pradumnasaraf** [comment]
Hey, @Muhammed-Rahif, thank you for opening an Issue.

Your profile already looks awesome.
#### Here are some of my recommendations -

- There is no need to add **myTopProjects()** because GitHub has special support for that, you already have pinned your top projects below.

If you need any kind of help, ping us here or on Discord [server](https://discord.com/invite/jZQs6Wu)

**Comment by Muhammed-Rahif** [comment]
@Pradumnasaraf Thanks for your valuable review! I removed that section now!

**Comment by eddiejaoude** [comment]
Reviewed on video for my YouTube channel

some notes
- add a bio
- try to have a profile pic of you
- try to do more issues and code reviews to have a more balanced contributing graph
- pin 4 repos
- customise your profile
