### ISSUE TITLE
[REVIEW] shrikanta8

### ISSUE THREAD

**Issue by shrikanta8** [EddieHubCommunity/support#3248]
### GitHub Profile Link

https://github.com/shrikanta8

**Comment by weeyin83** [comment]
Nice work!  I think the only thing I would suggest is maybe making the text a little bigger as it seems a bit lost in scale with the other items. 👍

**Comment by Pradumnasaraf** [comment]
Hey, @shrikanta8 , thank you for opening an Issue.

#### Here are some of my recommendations -

- Add a more descriptive Bio.
- Instead of pinning 6 repos, try to pin top 2/4 repos.
- Add Twitter handle under bio.
- More contributions :)

If you need any kind of help, ping us here or on Discord [server](https://discord.com/invite/jZQs6Wu)

**Comment by schmelto** [comment]
> Hey, @shrikanta8 , thank you for opening an Issue.
> 
> 
> 
> #### Here are some of my recommendations -
> 
> 
> 
> - Add a more descriptive Bio.
> 
> - Instead of pinning 6 repos, try to pin top 2/4 repos.
> 
> - Add Twitter handle under bio.
> 
> - More contributions :)
> 
> 
> 
> If you need any kind of help, ping us here or on Discord [server](https://discord.com/invite/jZQs6Wu)

Agree with that :)

**Comment by shrikanta8** [comment]
tysm @weeyin83 @Pradumnasaraf @schmelto 
i will edit it :)

**Comment by eddiejaoude** [comment]
Looks great, some suggestions

- profile picture to be of you (or something unique)
- add socials to GitHub section on the left
- maybe too much is animated
