### ISSUE TITLE
[REVIEW] Qadir Pervez

### ISSUE THREAD

**Issue by qadirpervez** [EddieHubCommunity/support#3256]
### GitHub Profile Link

https://github.com/qadirpervez

**Comment by Pradumnasaraf** [comment]
Hey, @qadirpervez  thank you for opening an Issue.

#### Here are some of my recommendations -

- Add a more descriptive Bio.
- Instead of pining 6 repos, try to pin the top 4 repos.
- Your profile looks commit heavy, try to distribute your contribution.

If you need any kind of help, ping us here or on Discord [server](https://discord.com/invite/jZQs6Wu)

**Comment by eddiejaoude** [comment]
Looks great, some suggestions

- great profile picture
- remove profile views badge
- maybe too many widgets - highly suggest reducing them
- pin 2 or 4 repos
- do more pull requests
