### ISSUE TITLE
[REVIEW] bobychaudhary

### ISSUE THREAD

**Issue by bobychaudhary** [EddieHubCommunity/support#3265]
### GitHub Profile Link

https://github.com/bobychaudhary

**Comment by Pradumnasaraf** [comment]
Hey, @bobychaudhary, thank you for opening an Issue.

#### Here are some of my recommendations -

- Add a more descriptive Bio.
- Instead of pinning 6 repos, try to pin top 2/4 repos.
- Try to make the profile page concise, by reducing badges and gifs

If you need any kind of help, ping us here or on Discord [server](https://discord.com/invite/jZQs6Wu)

**Comment by bobychaudhary** [comment]
Hey @Pradumnasaraf , thank you for reviewing my profile.
I'll make the necessary changes and I think you misread popular repositories to pinned repositories,
but ya I will pin my top 2/4 repos.

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf , thank you for reviewing my profile. I'll make the necessary changes and I think you misread popular repositories to pinned repositories, but ya I will pin my top 2/4 repos.

Ahh, my bad

**Comment by eddiejaoude** [comment]
Looks great, some suggestions

- remove profile views
- remove animated gif as takes up too much space
- do more open source contributiosn
- create more issues
