### ISSUE TITLE
[REVIEW] Navaneeth-Sharma

### ISSUE THREAD

**Issue by Navaneeth-Sharma** [EddieHubCommunity/support#3300]
### GitHub Profile Link

https://github.com/Navaneeth-Sharma

**Comment by Pradumnasaraf** [comment]
Hey, @Navaneeth-Sharma , thank you for opening an Issue.

#### Here are some of my recommendations -

- Add a more descriptive Bio.
- Instead of 6 try to pin top 2/4 repos.
- Try to use fewer cards (Language or streak).
- Bring **language and tools** section on the top.

If you need any kind of help, ping us here or on Discord [server](https://discord.com/invite/jZQs6Wu)

**Comment by Navaneeth-Sharma** [comment]
Thank you for suggestions, I will get it done.

**Comment by eddiejaoude** [comment]
Looks great, some suggestions

- 1 of the widgets doesn't work
- try to do more code reviews
- great profile picture
-
