### ISSUE TITLE
[REVIEW] Rabyâ Raghib (@rabraghib)

### ISSUE THREAD

**Issue by rabraghib** [EddieHubCommunity/support#3308]
### GitHub Profile Link

https://github.com/rabraghib

**Comment by Pradumnasaraf** [comment]
Hey, @Pankaj-SinghR, thank you for opening an Issue.

#### Here are some of my recommendations -
- Instead of Avatar, use your picture (It man be for privacy reasons, then ignore this :) )
- Add Bio
- Banner size can be reduced (totally on you :))
- Pin your top 2/4 repos.
- your profile looks commit heavy, try to distribute it (Diamond)

If you need any kind of help, ping us here or on Discord [server](https://discord.com/invite/jZQs6Wu)

**Comment by Pradumnasaraf** [comment]
Hey, @rabraghib, thank you for opening an Issue.

#### Here are some of my recommendations -
- Instead of Avatar, use your picture (It man be for privacy reasons, then ignore this :) )
- Add Bio
- Banner size can be reduced (totally on you :))
- Pin your top 2/4 repos.
- your profile looks commit heavy, try to distribute it (Diamond)

If you need any kind of help, ping us here or on Discord [server](https://discord.com/invite/jZQs6Wu)

**Comment by rabraghib** [comment]
Hey, @Pradumnasaraf!

for
- The banner and the avatar: they will be changed ASAP (whenever I have time to design them)
- Pining repos: I am currently documenting some of my projects so I can make them public & pin them
- contributions: I absolutely need to do more code reviews, issues, PRs..

 Thank you for your recommendations! I will definitely take them into consideration!

**Comment by eddiejaoude** [comment]
Looks great, some thoughts...

- pin 2 or 4 repos (not 3)
- latest blog post section seems empty
- years go back very far, is this a hack? suggest removing
