### ISSUE TITLE
[REVIEW] elishahyousaf

### ISSUE THREAD

**Issue by elishahyousaf** [EddieHubCommunity/support#3313]
### GitHub Profile Link

https://github.com/elishahyousaf

**Comment by Pradumnasaraf** [comment]
Hey, @elishahyousaf, thank you for opening an Issue.

#### Here are some of my recommendations -
- Instead of the ***OS*** section, you can create a section named `skills`, and put your all skill over there.
- Try to use even size social icons/tags.
- Instead of pinning 5 repos, pin top 4 repos (For making profile concise)


If you need any kind of help, ping us here or on Discord [server](https://discord.com/invite/jZQs6Wu)

**Comment by elishahyousaf** [comment]
Thank you.
I will work on it.

**Comment by eddiejaoude** [comment]
Looks great, some suggestions

- remove profile views badge
- pin 2 or 4 repos
- contribute more to open source and try to do more code reviews and issues
- I am not a fan of the trophies
