### ISSUE TITLE
[REVIEW] Pankaj-SinghR

### ISSUE THREAD

**Issue by Pankaj-SinghR** [EddieHubCommunity/support#3325]
### GitHub Profile Link

https://github.com/Pankaj-SinghR/

**Comment by Pradumnasaraf** [comment]
Hey, @Pankaj-SinghR, thank you for opening an Issue.
#### Here are some of my recommendations -
- consider adding a profile page, for help you can also refer to Github's [official docs](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme) 
- Instead of Avatar, use your picture (It man be for privacy reasons, then ignore this :) )
- Add Bio

If you need any kind of help, ping us here or on Discord [server](https://discord.com/invite/jZQs6Wu)

**Comment by eddiejaoude** [comment]
Looks great, some suggestions

- try to join some github organisations (e.g. EddieHub)
- pin 2 or 4 repos
- try to contribute to open source more
- try to do more issues

**Comment by Pankaj-SinghR** [comment]
sure, will do. Thanks
