### ISSUE TITLE
[REVIEW] Fayas Noushad Website

### ISSUE THREAD

**Issue by FayasNoushad** [EddieHubCommunity/support#3873]
### Portfolio link

https://fayasnoushad.github.io

**Comment by schmelto** [comment]
## Portfolio Review
### TLDR;

Your portfolio looks awesome! See the full details with my suggestions below.

---

### Full details

Your portfolio looks awesome! Here some suggestions from my side:

- Take a look at the repsonsivness of your website.
- Also I ran lighthouse scores on your website
![image](https://user-images.githubusercontent.com/30869493/164008359-cfe7e121-33d3-490f-92c0-e8dd07b4c55e.png)
you cold take a look at these results

Otherwise really solid potfolio

**Comment by ahmed82** [comment]
The profile looks good,
