### ISSUE TITLE
[REVIEW] Imran1509

### ISSUE THREAD

**Issue by imran1509** [EddieHubCommunity/support#5782]
### GitHub Profile Link

https://github.com/imran1509

**Comment by schmelto** [comment]
## Profile Review
### TLDR;

Your profile looks awesome! See the full details with my suggestions below.

---

### Full details

Your profile looks awesome! Here some suggestions from my side:

![image](https://user-images.githubusercontent.com/30869493/196124125-02b52119-0641-40d5-acf6-bafa5aaac028.png)
consider a link as [hashnode](test.com) instead of the full link

**Comment by imran1509** [comment]
Thanks for the feedback. I have fixed it

**Comment by eddiejaoude** [comment]
Looks great, reviewed on a live stream, here is some feedback

- awesome banner and profile picture 
- suggest pinning 4 repos
- and try to create more issues
