### ISSUE TITLE
[REVIEW] vivekpal1

### ISSUE THREAD

**Issue by vivekpal1** [EddieHubCommunity/support#6139]
### GitHub Profile Link

https://github.com/vivekpal1

**Comment by AliJafriETH** [comment]
Hey @vivekpal1, mate i checked your profile and here's what i think would add to it :))

## 1) You've misspelt "Coders" in your profile.

## 2) Try adding some colorful widget like a contribution graph.  

![x83v7m9069k4ze4pf22m](https://user-images.githubusercontent.com/114252412/208197169-f724b7c3-c904-4771-884f-1b702f1669c9.jpg)

## 3) Instead of writing the languages you use and know, you can use their icons.

![Screenshot (302)](https://user-images.githubusercontent.com/114252412/208197660-86648b9d-7dee-4557-aa8c-fd03ab6aa60e.png)


# These are the current things in my opinion, if you need help in doing this, let me know :))
# All the best 👍

**Comment by vivekpal1** [comment]
@AliJafriETH Thanks for the suggestions, It means a lot 😇
