### ISSUE TITLE
Review my Github Profile and Portfolio

### ISSUE THREAD

**Issue by Ayush7614** [EddieHubCommunity/support#794]
Items we can review on a live stream:

- GitHub profile : https://github.com/Ayush7614

- Portfolio : https://ayush7614.github.io/Portfolio/

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by schmelto** [comment]
I love your portfolio

**Comment by Ayush7614** [comment]
> I love your portfolio

Thanks bro @schmelto

**Comment by Nitesh-thapliyal** [comment]
## Your portfolio is amazing⭐

 ### Here are some points that I think can be improved:-

![Screenshot (625)](https://user-images.githubusercontent.com/53345517/106178137-6836c600-61bf-11eb-9d17-33b716d59962.png)

- I think it should be "**6 Projected Completed**"instead of  "**6 Project Complete**"

![Screenshot (626)](https://user-images.githubusercontent.com/53345517/106178262-91575680-61bf-11eb-819a-ec3a240a89af.png)

- If possible place GitHub and the LinkedIn button in front of the bullet point as it will look great😊

**Comment by Ayush7614** [comment]
Okk @Nitesh-thapliyal i will do it

**Comment by RutvikJ77** [comment]
Hey there @Ayush7614, great portfolio. I found a few key points which you can improve. 
There is a typo error in Contributer - its's Contributor
Another thing with Skill is maybe you can separate it into 2 columns instead of one. Just a design perspective.
![Screenshot 2021-01-29 at 10 53 55 AM](https://user-images.githubusercontent.com/45565999/106235295-77019500-6220-11eb-9717-730224f9c064.png)

**Comment by Ayush7614** [comment]
okk bro @RutvikJ77 i will do it

**Comment by imvisp** [comment]
1. you should write here contributor not developer
![temp](https://user-images.githubusercontent.com/75424375/106236029-06f40e80-6222-11eb-8066-30b4f5d8c6d2.png)

2.one more typo error - enthusiast not enthaustics
![t2](https://user-images.githubusercontent.com/75424375/106236387-bfba4d80-6222-11eb-9424-b88b9f5f6ed9.png)

**Comment by Ayush7614** [comment]
Okk bro i am surely correct it @imvisp

**Comment by eddiejaoude** [comment]
thanks for sharing @Ayush7614 . I will review in a live stream / video in the future 👍

**Comment by aathikahamed** [comment]
Speed up the typing speed

**Comment by schmelto** [comment]
Maybe you should take a look at the mobile view of your portfolio. 

![Screenshot_20210201_231813_com.android.chrome~2.jpg](https://user-images.githubusercontent.com/30869493/106525214-efe44380-64e3-11eb-8cc4-27b69ab9cb56.jpg)

**Comment by schmelto** [comment]
@nhcarrigan can you also add here the livestream label?

**Comment by schmelto** [comment]
I would recommend to remove the view count its duplicate and ist not very accurate
![image](https://user-images.githubusercontent.com/30869493/117691639-6caa4c00-b1bc-11eb-81d7-6ed7525639fa.png)
![image](https://user-images.githubusercontent.com/30869493/117691674-77fd7780-b1bc-11eb-9eac-70974b775dd9.png)

also take a look at the gif at the top in dark mode
![image](https://user-images.githubusercontent.com/30869493/117691756-8ea3ce80-b1bc-11eb-826e-eba91f59e008.png)


Otherwise I really like the profile

**Comment by rohank2502** [comment]
- If you are adding Hello First then no need to say Hi again!
- Liked the Black image that looks cool! 
- Two profile views counter 
- You can add about your projects also

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/biy__J7abMU

Looks good, some suggestions
- great description and links 👍 
- profile views I do not think are great (they can be faked)
- there are 2 profile view counters and with different numbers
- lots of wasted white space
- contribution graph is very commit heavy, suggest contributing in other ways too
