### ISSUE TITLE
Review my GitHub profile

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/support#851]
Items we can review on a live stream:

- GitHub profile: https://github.com/schmelto
- Portfolio: https://schmelto.github.io/portfolio/

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍 , I will review on a live stream soon 🤓

**Comment by schmelto** [comment]
Oh no github action this is still relevant 🙈

**Comment by Rahma-AlWadhahi** [comment]
Cool profile!! One suggestion though, maybe try to put contact form and other badges in separate sections or add more padding, because the submit button looks like it belongs to the other badges too!?
![D3AE2B99-8F49-468A-8444-16D20B8D5194](https://user-images.githubusercontent.com/61970868/115266050-e5cbfb80-a148-11eb-814c-ec1210974ad8.jpeg)

**Comment by schmelto** [comment]
@Rahma-AlWadhahi yeah that's a great idea will take care of this :)

**Comment by siddharthdayalwal** [comment]
You can also work on having a light mode for viewers not comfortable with dark mode! :nerd_face:

**Comment by Prathamesh-Shanbhag** [comment]
Consider using Aria-Labels for Accessibility!

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/MrS_jAJ8l0o

Looks great 👍 

- change mailto to FormSpree
- light mode as well as dark mode
- accessibility with the animation
