### ISSUE TITLE
[BUG] Discord document

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/support#8671]
### Description of the bug

Continuation from discussion in PR https://github.com/EddieHubCommunity/support/pull/8669 by @LeaDevelop 

This is what I currently see with my entry level without touching the Browse Channels option in the discord (I used that now and can see them all). Screenshot took before I touched Browse Channels option
![eddihub-discord](https://github.com/EddieHubCommunity/support/assets/104503492/9300e259-b858-44b9-9aa3-46f74cf1cb17)

My discord level according to Becca Lyria bot is 3.
I would propose that you list all channels and their descriptions members are able to reach and also mention to take a look at Browse Channel to see all other channels.
If you lock some channels after certain level of activity, would also list and explain what action has to be taken to reach it :)

Summary:
- would add disclaimer to use Browse Channels feature to find full channel list. 
    - perhaps natural flow for others. I use discord for +8 years and still missed it haha
- would list all channels, so people know what they can find and if they don't see it, they'll eventually look around and find the Browse Channels which empowers summary point one
- consider helper role in future, or add disclaimer high chance you'll get tagged if you use certain roles. I joined community and read through initial code of conduct and had idea that it'll be vibrant interactive journey but not sure if all perceive the entry into your community like that (Most common in my surroundings when I talk to people, they join discord servers and before anything else is done, they mute server for any pinging and that's understanding when you are in 10 ore more servers, discord goes brrrrrr 😅)

GENERAL DISCUSSION
#readme - ⚠️ this one is not listed and explained currently
#roles - ⚠️it only enlists if one enters it via readme channel and then it vanishes. BTW I didn't realize that if I pick certain role in the discord channel, members will assume I am expert in that area. Have you considered adding a helper role, if people want to be tagged for topics, although that may not really solve the problem, cos you'd have to separate interested into topic and able and willing to help on specific topic :) long separate topic, no need to address here.
#general  ✔️ 
#help  ✔️ 
#content-share - ⚠️ this one I see after using Browse Channels feature
#career - ⚠️ this one is currently not listed and explained
#bot-chat - ⚠️ this one I see after using Browse Channels feature

DAILY
#standup ✔️ 
#wellness ✔️ 
#achievements - ⚠️ this one I see after using Browse Channels feature

COMMUNITY DISCUSSION
#ideas ✔️ 
#first-timers ✔️ 
#public-speaking ✔️ 
#maintainers - ⚠️ this one is not explained in the file
#hackathons - ⚠️ this one i don't see, maybe cos of my entry level

RadioEddieStage 00/99 - ⚠️ Maybe also add description here, is this for hangout when you got events going on? Which also leads me to question do you consider having create channels on demands for members, when they help each other, or does all run through pull requests and text chat? Sometimes it's easier to convey via screen share and being able to explain show, explain and discuss problem via voice.

Locked channels
#TeamEddie
#Maintainers
#Sponsors

### Project stack or language (e.g. front-end)

docs

### Working Environment (e.g. operating system, browser, device)

n/a

**Comment by LeaDevelop** [comment]
Thanks for posting an Issue @eddiejaoude was about to do it now. I didn't prepare the PR yet, blocked me hour to set me up and take care of it for Sunday. _(Not spending much time in front of screens outside of work atm due to migraine insomnia combo week 🙄)_ 

You can count on me prepping the PR and then someone who's established maintainer or you can review and adapt any missing parts I'd have as a newbie of community here 😊 

If you have any specific take already on the brought up observations, please do share them. I'll make sure they are included into my first draft 🥳 

The scope for this PR:
- add disclaimer to use Browser Channels feature
- update channel with missing ones and their descriptions

For ideas would create discussions in https://github.com/orgs/EddieHubCommunity/discussions or you'd like me to create new issues (I didn't check yet but will if you had any in past)?
- helper role
- voice channels (I am personally curious if there is reason why that's not feature used, then obviously not going to create a discussion for it, feel free to poke me at any documentation, I merely just started reading through one in your main repo)

**Comment by LeaDevelop** [comment]
@eddiejaoude this can be marked as resolved as you've merged it, thank you!

**Comment by eddiejaoude** [comment]
Thank you @LeaDevelop for following up 👍
