### ISSUE TITLE
Gradientiser- a  CSS gradient generator web app

### ISSUE THREAD

**Issue by Nirbhayparmar** [EddieHubCommunity/support#937]
Hey Eddie,

I am Nirbhay Parmar, I attended your live workshop on Girlscript foundation's YouTube channel, and today I am selected as a participant in Girlscript summer of code 2021. Thank you for 
your workshop.

This is the link to my repo- [Gradientiser](https://github.com/Nirbhayparmar/gradientiser-BgGenerator) 

Check it live [here.](https://nirbhayparmar.github.io/gradientiser-BgGenerator/) 

And i also want to know that is my project is worth it as open-source or i should say is useful to anyone because there are many websites out there having lot more features then my project.
Please give your opinion on the usefulness of this project.

**Comment by eddiejaoude** [comment]
Thank you for sharing 👍 . I will review on a live stream / video soon 🤓

**Comment by schmelto** [comment]
Make it open source 🚀

**Comment by Nirbhayparmar** [comment]
It is already open source. I have also added MIT license to it.

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/MrS_jAJ8l0o

Looks good 👍 , some thoughts 

repo
- screenshot in the readme would be great
- use repo description near live demo link
- recommend being consistent with file naming conventions, some have `-` some are camelcase
- suggest having a code of conduct, more info found in insights tab https://github.com/Nirbhayparmar/gradientiser-BgGenerator/community
- using issues will help get more people involved in your project

live demo
- have the text with a background because with some colours it is difficult to read
- code to be in a code block would be much clearer

**Comment by Nirbhayparmar** [comment]
Thank you so much @eddiejaoude for reviewing my project and also thanks for your suggestions. Surely work upon this.
