### ISSUE TITLE
Please review my GitHub profile

### ISSUE THREAD

**Issue by PulkitSinghDev** [EddieHubCommunity/support#948]
Please review my GitHub profile:-
[PulkitSinghDev](https://GitHub.com/pulkitSinghDev)

**Comment by Pulkit0076** [comment]
@eddiejaoude sir please review my GitHub profile :)

**Comment by vinzvinci** [comment]
OMG you have cool GitHub profile! :)  

Suggestion:
- Rename your `Issue Title` into `Review my GitHub profile`

**Comment by PulkitSinghDev** [comment]
@vinzvinci Thank you :)

**Comment by eddiejaoude** [comment]
Thanks for sharing, I will review on a video or live stream soon. In the meantime I see the community are already giving you feedback 💥

**Comment by ahammadshawki8** [comment]
> Thanks for sharing, I will review on a video or live stream soon. In the meantime, I see the community is already giving you feedback.

You can review my GitHub profile as well @eddiejaoude 😇

**Comment by ahammadshawki8** [comment]
>Please review my GitHub profile:-
PulkitSinghDev

Great GitHub, keep up the good work 🥳

**Comment by PulkitSinghDev** [comment]
@ahammadshawki8 Thanks 

> > Please review my GitHub profile:-
> > PulkitSinghDev
> 
> Great GitHub, keep up the good work 🥳

**Comment by Vyvy-vi** [comment]
The profile looks really nice-!
However, here are a few points on the profile:
- Try serving your images via links (from a cdn/imgur).
Q) Why?
Ans- Less load on a github repo, since it won't have to track the images. Moreover, images served through cdn might load faster(something like using the discord link of the image after putting it on there or making imgur link for the image)
*tho I would suggest you get a second opinion on this from someone
- Have a look at pinning repos under the profile, rather than the default "popular repos".
Q) Why?
Ans- You should try to put forward your projects that _showcase_ all of your skills(you have an impressive list of set of skills, if the pinned repos reflect that, it would have a great effect on people potentially hiring you or choosing you for projects)
- **Showcase** your achievements:
like "Google Crowdsource Top contributor": Pin the repositories in which you contributed for that evaluation to show your contribution, and skill 
- Consider removing the "Profile Views" Badge
Q) Why?
Ans- The information in there is usually refreshes to your profile page, and thus might not be accurate with respect to "Views", but it's up to you :+1:

Hope to see more from your side :)

**Comment by Vyvy-vi** [comment]
> You can review my GitHub profile as well @eddiejaoude 😇

You can open an issue for the review: (this would ensure that Eddie doesn't miss track of your profile 🙂 )
https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=open+source+review&template=review-my-open-source-link.md&title=

**Comment by ahammadshawki8** [comment]
> > You can review my GitHub profile as well @eddiejaoude 😇
> 
> @ahammadshawki8
> You can open an issue for the review: (this would ensure that Eddie doesn't miss track of your profile 🙂 )
> https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=open+source+review&template=review-my-open-source-link.md&title=

OK, thanks.

**Comment by PulkitSinghDev** [comment]
> The profile looks really nice-!
> However, here are a few points on the profile:
> 
> * Try serving your images via links (from a cdn/imgur).
>   Q) Why?
>   Ans- Less load on a github repo, since it won't have to track the images. Moreover, images served through cdn might load faster(something like using the discord link of the image after putting it on there or making imgur link for the image)
>   *tho I would suggest you get a second opinion on this from someone
> * Have a look at pinning repos under the profile, rather than the default "popular repos".
>   Q) Why?
>   Ans- You should try to put forward your projects that _showcase_ all of your skills(you have an impressive list of set of skills, if the pinned repos reflect that, it would have a great effect on people potentially hiring you or choosing you for projects)
> * **Showcase** your achievements:
>   like "Google Crowdsource Top contributor": Pin the repositories in which you contributed for that evaluation to show your contribution, and skill
> * Consider removing the "Profile Views" Badge
>   Q) Why?
>   Ans- The information in there is usually refreshes to your profile page, and thus might not be accurate with respect to "Views", but it's up to you 👍
> 
> Hope to see more from your side :)

Thank you so much for the guidance 💯 🥇 :)

**Comment by nhcarrigan** [comment]
> (something like using the discord link of the image after putting it on there or making imgur link for the image)

Please don't use Discord's CDN as an image host. 🙂

**Comment by PulkitSinghDev** [comment]
> > (something like using the discord link of the image after putting it on there or making imgur link for the image)
> 
> Please don't use Discord's CDN as an image host. 🙂

ok, thanks

**Comment by PulkitSinghDev** [comment]
Hey everyone, I have re-designed the website, please do recheck it once :)

**Comment by PulkitSinghDev** [comment]
@nhcarrigan ohk will check it out 
Thank you so much for letting me know :)

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/MrS_jAJ8l0o

Looks good 👍 , some thoughts 

- great illustrations / cartoons 👍 
- my octocat takes up a lot of space, suggest making it smaller and aligned to the side
- about me is all in bold, suggest making certain parts in bold only to stand out
- lots of organisations which looks good 👍 
-
