### ISSUE TITLE
PLEASE review my GitHub profile and Portfolio

### ISSUE THREAD

**Issue by ahammadshawki8** [EddieHubCommunity/support#971]
Here is my [GitHub Profile](https://github.com/ahammadshawki8) and [Portfolio](https://ahammadshawki8.github.io/).
@eddiejaoude you can review it on live streams/videos.
Community members also please review it and give feedback. It will be helpful for me. 
Thanks.

**Comment by PulkitSinghDev** [comment]
HI there, I have checked your portfolio and github profile, and both looks good, But please note these things:-
 - Your portfolio's ui is great but try to make the user experience better because its not much good enough while talking about User Experience according to my experience
 - Please try to have equal amount of pull requests, issues, etc. as well
![image](https://user-images.githubusercontent.com/71369943/108940453-60acf480-7679-11eb-984a-adc394a39805.png)
 - It would be great of you add the header in the starting of the website , because many times people gets confused
![image](https://user-images.githubusercontent.com/71369943/108940608-ac5f9e00-7679-11eb-89d9-45019f2adaef.png)
 ### And that's all , Great work!!
 # Even I started when I was almost 12 and now I am 13 :)

**Comment by eddiejaoude** [comment]
Thanks for sharing @ahammadshawki8 👍 I will review on a live stream / video soon 🤓

**Comment by eddiejaoude** [comment]
Reviewed on live stream https://youtu.be/MrS_jAJ8l0o

Looks good 👍 , some thoughts 

- scroll button would have a nicer effect if it gradually scrolled to the next section
- email could be a clickable link
- tech stack is quite busy, maybe group them together (some could be removed like vscode, regex etc)
- great landing page

**Comment by ahammadshawki8** [comment]
Ok thanks,  I am working on the points.
